#!/bin/sh
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2017 Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
# Copyright (C) 2018 Frédéric Pierret (fepitre) <frederic@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e
if [ "${VERBOSE:-0}" -ge 2 ] || [ "${DEBUG:-0}" -eq 1 ]; then
    set -x
fi

if [ $# -lt 3 ]; then
    echo "Usage: $0 source_dir input output" >&2
    exit 1
fi

source_dir="$1"
input="$2"
output="$3"

# Handle the case where .spec.in (input) does not exist
# and .spec does (output).
if [ ! -e "${input}" ] && [ -e "${output}" ]; then
    echo "Spec file '${output}' already exists. Skipping."
    exit
fi

cp "$input" "$input.tmp"

# Handle sources with multiples package/version/release:
# 'version' must contains list of version number corresponding to @VERSION@ @VERSION1@ ...
# 'rel', must contains list of release number corresponding to @REL@ @REL1@ ...
while read -r ver
do
    if [ -z "$vnum" ]; then
        sed -i "s|@VERSION@|$ver|g" "$input.tmp"
    else
        sed -i "s|@VERSION$vnum@|$ver|g" "$input.tmp"
    fi
    vnum=$(( vnum + 1 ))
done < "${source_dir}/version"

if [ -e "${source_dir}/rel" ]; then
    while read -r rel
    do
        if [ -z "$rnum" ]; then
            sed -i "s|@REL@|$rel|g" "$input.tmp"
        else
            sed -i "s|@REL$rnum@|$rel|g" "$input.tmp"
        fi
        rnum=$(( rnum + 1 ))
    done < "${source_dir}/rel"
else
    if grep -q "@REL@" "$input.tmp"; then
        echo "@REL@ found in spec, but no $source_dir/rel file" >&2
        exit 1
    fi
fi

# Handle default rel and backend_vmm
sed -i \
    -e "s:@BACKEND_VMM@:${BACKEND_VMM}:g" "$input.tmp"

# Handle changelog
if grep -q "@CHANGELOG@" "$input.tmp"; then
    "$(dirname "$0")"/generate-changelog "${source_dir}" "$input.tmp"
fi

# Handle openSUSE package naming differences
if [ "$DIST_NAME" = "opensuse-leap" ] || [ "$DIST_NAME" = "opensuse-tumbleweed" ]; then
    # Handle simple different package names
    sed -i \
        -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)python3dist(sphinx)$/\1Requires:\2python3-Sphinx/g" \
        -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)python\(3\|%{python3_pkgversion}\)-sphinx$/\1Requires:\2python\3-Sphinx/g" \
        -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)python\(3\|%{python3_pkgversion}\)-yaml$/\1Requires:\2python\3-PyYAML/g" \
        -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)python\(3\|%{python3_pkgversion}\)-pyyaml$/\1Requires:\2python\3-PyYAML/g" \
        -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)netpbm-progs$/\1Requires:\2netpbm/g" \
        -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)xorg-x11-drv-dummy$/\1Requires:\2xf86-video-dummy/g" \
        "$input.tmp"
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)pycairo$/\1Requires:\2python2-cairo/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)PyYAML$/\1Requires:\2python2-PyYAML/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)dejavu-sans-fonts$/\1Requires:\2dejavu-fonts/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)libGL-devel$/\1Requires:\2Mesa-libGL-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)libGLU-devel$/\1Requires:\2glu-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)dbus-devel$/\1Requires:\2dbus-1-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)dbus-glib-devel$/\1Requires:\2dbus-1-glib-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)edk2-tools$/\1Requires:\2ovmf-tools/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)edk2-ovmf$/\1Requires:\2qemu-ovmf-x86_64/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]a-z0-9-]\+\)ipxe-roms-qemu\([[:space:]a-z0-9-]*\)/\1Requires:\2qemu-ipxe\3/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]a-z0-9-]\+\)seabios-bin\([[:space:]a-z0-9-]*\)/\1Requires:\2qemu-seabios\3/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)pixman-devel$/\1Requires:\2libpixman-1-0-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)yajl-devel$/\1Requires:\2libyajl-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)iscsi-initiator-utils$/\1Requires:\2open-iscsi/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)numactl-devel$/\1Requires:\2libnuma-devel/g" \
    #    -e "s/^BuildRequires:\([[:space:]]\+\)python%{python3_pkgversion}-hidapi\(.*\)/BuildRequires:\1libhidapi-devel\2/g" \
    #    -e "s/^Requires:\([[:space:]]\+\)python%{python3_pkgversion}-hidapi\(.*\)/Requires:\1python%{python3_pkgversion}-hidraw0\2/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)elfutils-libelf-devel$/\1Requires:\2libelf-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)nettle-devel$/\1Requires:\2libnettle-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)audit-libs-devel$/\1Requires:\2audit-devel/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)bzip2-devel\(.*\)/\1Requires:\2libbz2-devel\3/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)acpica-tools\(.*\)/\1Requires:\2acpica\3/g" \
    # These are not a separate package but contained in the base package
    sed -i \
        -e "s/^\(Build\)\?Requires:\([[:space:]a-z0-9-]\+\)perl-generators\([[:space:]a-z0-9-]*\)/\1Requires:\2perl\3/g" \
        "$input.tmp"
    #    -e "s/^\(Build\)\?Requires:\([[:space:]a-z0-9-]\+\)perl-interpreter\([[:space:]a-z0-9-]*\)/\1Requires:\2perl\3/g" \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)systemd-units$/\1Requires:\2systemd/g" \
    #    -e "s/^\(Build\)\?Requires:[[:space:]]\+glusterfs-api-devel.*//g" \
    #    "$1.tmp"
    # Make sure python setuptools is also installed when python devel package is
    #sed -i \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)python\(2\|3\|%{python3_pkgversion}\)-devel$/\1Requires:\2python\3-devel python\3-setuptools/g" \
    #    "$1.tmp"
    # Make sure graphviz is also installed when asciidoc package is
    #sed -i \
    #    -e "s/^\(Build\)\?Requires:\([[:space:]]\+\)asciidoc\(.*\)/\1Requires:\2asciidoc\3 graphviz/g" \
    #    "$1.tmp"
    # Make sure parted is also installed when parted devel package is
    #sed -i \
    #    -e "s/^BuildRequires:\([[:space:]]\+\)parted-devel$/BuildRequires:\1parted-devel parted/g" \
    #    "$1.tmp"
fi

cat "$input.tmp" > "$output"
rm -rf "$input.tmp"

# TODO: improve handlers
